[theme]
primaryColor = "#ffffff"
backgroundColor = "#0a0a0a"
secondaryBackgroundColor = "#111111"
textColor = "#e0e0e0"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
